name: ExotiaLobby
version: 1.2
author: exotia.net Team
website: https://exotia.net/
description: Minecraft Paper plugin for exotia.net lobbies
main: net.exotia.plugins.lobby.LobbyPlugin
api-version: 1.20
softdepend: [ PlaceholderAPI, Oraxen ]